### ISSUE TITLE
[js] does not compile with emscripten >= 1.38

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/olm#12]
as 1.38 defaults to wasm, but wasm is apparently not compatible with our pre and post script somehow
(see also https://github.com/Kagami/ffmpeg.js/issues/44#issuecomment-392248729 )

so we need to add `-s WASM=0` to the `EMCCFLAGS`

**Comment by uhoreg** [comment]
even after adding `-s WASM=0`, there are still issues with emscripten 1.38

* `Module['Runtime']` is no longer defined.  `stackSave` and `stackRestore` seem to be in `Module` directly now, rather than in `Module['Runtime'`
* `Module['allocate']` is no longer defined (it seems to be a global now?)
* even after fixing these issues, the unit tests fail, saying `abort("Assertion failed: undefined").` :frowning_face:

**Comment by dbkr** [comment]
There's now a pending PR in olm for this.
