### ISSUE TITLE
Olm doc typo

### ISSUE THREAD

**Issue by dest4** [matrix-org/olm#14]
In http://git.matrix.org/git/olm/about/docs/olm.rst, if I am not mistaken, near "Advancing the chain key", the term `C i, j - i` should be replaced with `C i, j - 1`.

**Comment by ara4n** [comment]
oops - homoglyph attack! fixed; thanks :)

http://git.matrix.org/git/olm/commit/?id=8f6e0557eeb3afe1088ce1abfc7351eb697eea24
