### ISSUE TITLE
Megolm doc: nitpicking question about ratchet

### ISSUE THREAD

**Issue by dest4** [matrix-org/olm#15]
Hi,
I do not fully understand the following sentence in the [Megolm doc](https://git.matrix.org/git/olm/about/docs/megolm.rst).

> This scheme allows the ratchet to be advanced an arbitrary amount forwards while needing at most 1023 hash computations.

If I understood correctly the way the ratchet advances, the worst case scenario would be to advance from `i=0` to `i=2^32 - 1`, assuming that `i` is a 32-bit counter that cannot overflow (can it?).
- 255 forwards would be needed to go from `i=0` to `i=2^32 - 2^24`
- 255 forwards would be needed to go from `i=2^32 - 2^24` to `i=2^32 - 2^16`
- 255 forwards would be needed to go from `i=2^32 - 2^16` to `i=2^32 - 2^8`
- 255 forwards would be needed to go from `i=2^32 - 2^8` to `i=2^32 - 1`

That makes 1020 hash computations, not 1023. Am I wrong?
Not that it's particularly important, but I am afraid to have an erroneous understanding of the whole thing.

**Comment by ara4n** [comment]
it sounds to me like a mental arithmetic thinko; the difference between `4*(2^8 - 1)` and `(4*2^8) - 1`. @richvdh, does this sound right?

**Comment by richvdh** [comment]
> @richvdh, does this sound right?

yes.

**Comment by dest4** [comment]
OK thanks for the clarification

**Comment by ara4n** [comment]
this got fixed back in sept.

**Comment by ara4n** [comment]
...except it didn't.

**Comment by ara4n** [comment]
now fixed in https://gitlab.matrix.org/matrix-org/olm/commit/214908ace54604da669b015cfda7c0496918dfc0
