### ISSUE TITLE
Source git repo is not accessible

### ISSUE THREAD

**Issue by minlexx** [matrix-org/olm#18]
https://git.matrix.org/git/olm 404 not found, https://git.matrix.org/ Apache2 Debian Default Page.
Is there a mirror of a source code somewhere?

**Comment by poljar** [comment]
There is one here https://gitlab.gnome.org/jhaye/olm

**Comment by jryans** [comment]
This is on the list to restore after the [security incident](https://matrix.org/blog/2019/04/11/security-incident/).

**Comment by arthurlutz** [comment]
I think this mirror is a bit outdated (missing 3.0 version)

**Comment by turt2live** [comment]
The git repository is still down, however the npm packages are back for anyone interested.

**Comment by minlexx** [comment]
Now here? https://github.com/Nheko-Reborn/nheko/commit/33b1f37e378d85a1efc685f690c3a92cf24d2ebf#diff-e23a3893b97f38154e05ff8b38f225ee

**Comment by jryans** [comment]
Yes, https://gitlab.matrix.org/matrix-org/olm is the new source address. I have updated the README to state that.
