### ISSUE TITLE
Provide pkgconfig file

### ISSUE THREAD

**Issue by encombhat** [matrix-org/olm#19]
Please provide a pkgconfig file such as `libolm.pc` while installing the library to allow linking the lib via pkg-config.

**Comment by uhoreg** [comment]
possibly useful documentation: https://people.freedesktop.org/~dbn/pkg-config-guide.html#writing (thanks @poljar )

**Comment by uhoreg** [comment]
This was fixed by https://gitlab.matrix.org/matrix-org/olm/-/commit/21ba95ade58dcdc2ab2a33467c3eb3d6a2909a46
