### ISSUE TITLE
CMakeLists.txt: add env vars to target_include_directories

### ISSUE THREAD

**Issue by a-andreyev** [matrix-org/olm#21]
Provided solution: https://github.com/a-andreyev/olm/commit/5421c05f86e6936ccfb381d263fe35aab0b230da

This makes possible to use Olm as an in-tree dependency too (not only as a system-side package). For example, for the [libQtOlm](https://gitlab.com/b0/libqtolm/merge_requests/3) project to organize CI builds for the [libQuotient](https://github.com/quotient-im/libQuotient) based projects (like [Quaternion](https://github.com/quotient-im/Quaternion))

Would be happy to remove my fork and use matrix-org repo instead then :slightly_smiling_face:

**Comment by uhoreg** [comment]
Merged: https://gitlab.matrix.org/matrix-org/olm/commit/aa0c9ab6b51d182cb78ab4cc75c81c0054765bde

Thanks
