### ISSUE TITLE
jitpack is unreliable for Android packages

### ISSUE THREAD

**Issue by MischaRo** [matrix-org/olm#23]
When building an android application, I get the following error:

``Could not find olm.jar (org.matrix.gitlab.matrix-org:olm:3.1.2).
Searched in the following locations:
    https://jitpack.io/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar``

it looks like jitpack is trying to access an outdated reference that is still pointing to the https://github.com/matrix-org/olm/ -directory, even though it has been moved to https://gitlab.matrix.org/matrix-org/olm/

**Edit from maintainer:** This is an issue with jitpack being unreliable, and we have no control over it.  If you run into this problem, the only thing you can do is wait try again later.

**Comment by uhoreg** [comment]
Jitpack seems to have intermittent failures as per https://github.com/jitpack/jitpack.io/issues/3908.  The olm sources were never at github.com/matrix-org/olm/, so there's no reason that jitpack would be referencing that location.

**Comment by awesome-manuel** [comment]
@uhoreg look at https://jitpack.io/#matrix-org/olm. The hashes under "Release" are exactly those of the commits in https://github.com/matrix-org/olm/commits/master

**Comment by uhoreg** [comment]
AIUI, jitpack just pulls from whatever git repository it guesses from the URL that you give it.  https://jitpack.io/#org.matrix.gitlab.matrix-org/olm would point to the correct repository, and looking at the OP's post, they're using org.matrix.gitlab.matrix-org:olm.

**Comment by toshanmugaraj** [comment]
Could not find org.matrix.gitlab.matrix-org:olm:3.1.2.
Searched in the following locations:
  - https://jitpack.io/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.pom
  - https://jitpack.io/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar
  - https://github.com/vector-im/jitsi_libre_maven/raw/master/releases/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.pom
  - https://github.com/vector-im/jitsi_libre_maven/raw/master/releases/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar
  - https://dl.google.com/dl/android/maven2/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.pom
  - https://dl.google.com/dl/android/maven2/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar
  - https://maven.google.com/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.pom
  - https://maven.google.com/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar
  - https://jcenter.bintray.com/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.pom
  - https://jcenter.bintray.com/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar
  - https://s3.amazonaws.com/repo.commonsware.com/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.pom
  - https://s3.amazonaws.com/repo.commonsware.com/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar
  - https://oss.sonatype.org/content/repositories/snapshots/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.pom
  - https://oss.sonatype.org/content/repositories/snapshots/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar
Required by:
    project :vector > com.github.matrix-org:matrix-android-sdk:v0.9.27 > com.github.matrix-org.matrix-android-sdk:matrix-sdk:v0.9.27
    project :vector > com.github.matrix-org:matrix-android-sdk:v0.9.27 > com.github.matrix-org.matrix-android-sdk:matrix-sdk-crypto:v0.9.27

**Comment by tonyrewin** [comment]
having the same problem now. Is there any method to build an application? I've tried `implementation 'com.github.matrix-org:olm:master-SNAPSHOT'` but no success :(

**Comment by uhoreg** [comment]
> `implementation 'org.matrix.gitlab.matrix-org:olm:3.1.4'` works fine

It is unlikely that `implementation 'org.matrix.gitlab.matrix-org:olm:3.1.4'` would behave any better.  The issue is that jitpack is unreliable, so sometimes it works and sometimes it doesn't, and it's likely that it just so happened that when you tried `3.1.4`, it served up the package correctly.

To make it clear, this is an issue with jitpack that we have no control over.  If you run into this problem, the only thing to do is to wait and try again later.

**Comment by uhoreg** [comment]
We're working on hosting the packages from our own Maven repository on gitlab.matrix.org, so that we won't have to rely on jitpack any more

**Comment by uhoreg** [comment]
The latest version of olm is now available on [Maven Central](https://search.maven.org/artifact/org.matrix.android/olm-sdk), and newer versions will be uploaded there.  Please use that instead of jitpack.
