### ISSUE TITLE
Risk of logging ratchet_key in olm::Session::describe

### ISSUE THREAD

**Issue by alinradut** [matrix-org/olm#26]
In Olm 3.1.4 we have the possibility of logging session information via olm::Session::describe. I am trying to debug an issue between two users which suddenly can't communicate any longer.

How big of a risk would be to log the ratchet_key.public_key from their respective sender/receiver chains so I can understand how their chains became out of sync?

Also, is there a plan to store the reader.counter and reader.ratchet_key.public_key after a (failed?) olm::Ratchet::decrypt? It's really hard to differentiate between a BAD_MESSAGE_MAC error caused by an out of sync session and a message being decrypted twice (if for example the user deleted the original message). 

With this information we could catch these mismatched sessions and form an idea about why this is happening and prevent it.

**Comment by poljar** [comment]
The spec documents how to recover from mismatched sessions, preventing it completely is impossible. One common failure mode is restoring old sessions from backup.

MSC for this can be found [here](https://github.com/matrix-org/matrix-doc/pull/1719).
Spec entry can be found[here](https://matrix.org/docs/spec/client_server/latest#recovering-from-undecryptable-messages).

Long story short, you abandon the mismatched session and create a new one.

As to your question, the ratchet public keys are exchanged between the session owners in the messages. They are public and there is no danger in logging them.
