### ISSUE TITLE
Cannot "pip install python-olm" Linux Mint / Python 3.6/3.7/3.8

### ISSUE THREAD

**Issue by andreasbuhr** [matrix-org/olm#27]
Hi there,

whenever I try to "pip install python-olm", I get first an error message 

`make: *** No rule to make target '../include/olm/olm.h', needed by 'include/olm/olm.h'.  Stop.`

Then the error message:

`build/temp.linux-x86_64-3.6/_libolm.c:544:18: fatal error: olm/pk.h: No such file or directory`

The full output is in 
[buildout.txt](https://github.com/matrix-org/olm/files/4402255/buildout.txt)

libolm-dev is installed:
```
(virtualenv36) andreas@PC-01:~$ apt search libolm-dev
i   libolm-dev                                                                             - development files for the olm Double Ratchet implementation                                      
p   libolm-dev:i386                                                                        - development files for the olm Double Ratchet implementation                                      
(virtualenv36) andreas@PC-01:~$ 
```

This is a Linux Mint (tessa/bionic) system.

**Comment by poljar** [comment]
The first error is harmless the second one seems to indicate that your libolm-dev might be too old.

What are the versions of those packages you installed?

**Comment by andreasbuhr** [comment]
Thanks for your quick reply

```
andreas@PC-01:~$ apt-cache policy libolm-dev
libolm-dev:
  Installed: 2.2.2+git20170526.0fd768e+dfsg-1
  Candidate: 2.2.2+git20170526.0fd768e+dfsg-1
  Version table:
 *** 2.2.2+git20170526.0fd768e+dfsg-1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
andreas@PC-01:~$ 
```

**Comment by poljar** [comment]
Yeah that's the problem, the installed libolm-dev is too old.

You'll need to find a 3.1 version of that package, the header that is needed to build the bindings is only available in that version.

**Comment by andreasbuhr** [comment]
Oh thanks, sorry for the noise

**Comment by PhieF** [comment]
Same issue with 3.1 here
