### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by goerz** [matrix-org/olm#28]
While the README contains instructions on how to *build* the `olm` library, I was not able to find any information how to *install* it such that I can then install the `requirements.txt` for [weechat-matrix](https://github.com/poljar/weechat-matrix) on macOS.

Building the library with `cmake` (as well as the python bindings) finished without error, but where do I go from there? A `make install` does not work (errors with `install: illegal option -- D`)

**Comment by goerz** [comment]
For now, I managed to install the library into homebrew, see https://github.com/matrix-org/olm/issues/29#issuecomment-611759837

**Comment by richvdh** [comment]
closing as a dup of #29
