### ISSUE TITLE
installation instructions for macOS

### ISSUE THREAD

**Issue by goerz** [matrix-org/olm#29]
I have not been able to install this library on macOS. Could you provide a [homebrew](https://brew.sh) formula?

**Comment by goerz** [comment]
I managed to get olm to install with the following:
~~~
class Olm < Formula
  desc "Implementation of the olm and megolm cryptographic ratchets"
  homepage "https://gitlab.matrix.org/matrix-org/olm"
  url "https://gitlab.matrix.org/matrix-org/olm/-/archive/3.1.4/olm-3.1.4.tar.gz"
  sha256 "1ca9926ce71d778fb7352d1ee77513194db8c7f49c0d69d38ac49ec3bafcea38"
  depends_on "cmake" => :build
  def install
    system "cmake", "--version"
    system "cmake", ".", '-Bbuild', *std_cmake_args
    system "cmake", "--build", 'build'
    makeargs = %W[
        PREFIX=#{prefix}
        SYSCONFDIR=#{etc}
        CC=#{ENV.cc}
        CFLAGS=#{ENV.cflags}
        LDFLAGS=#{ENV.ldflags}
        NO_TCLTK=1
    ]
    inreplace "Makefile", "-Dm644", "-m644"
    inreplace "Makefile", "-Dm755", "-m755"
    system "make", "install", *makeargs
  end

  test do
    system "false"
  end
end
~~~

**Comment by richvdh** [comment]
If you'd like to provide a patch as per https://gitlab.matrix.org/matrix-org/olm/-/blob/master/CONTRIBUTING.md, we'd be glad to consider it.

**Comment by anantthebiker** [comment]
Thanks a lot man @goerz . These matrix people are good for nothing. @poljar  They have left things half baked. No guide on how to link OLM with nio or how to install python-olm successfully on MAC.

**Comment by poljar** [comment]
I'm sorry you feel this way, there have been a bunch of people that asked how to install python-olm on various operating systems, I don't think I ignored any of them.

As to why there isn't a Mac specific guide, I don't use a Mac and I'm not confident enough to write a guide for an operating system I don't use and have no way to test the correctness of. If you are stuck, opening an issue or asking in the matrix-nio room might have been fruitful.

Is there anything more concrete about what's wrong with matrix-nio? API design input is always welcome, though we're a bit stuck with some decisions since we don't want to break absolutely everything.

If so, please feel free to open bug reports, suggestions and even PRs on the matrix-nio github.

Thanks, Damir.

**Comment by goerz** [comment]
@anantthebiker I understand your frustration, but telling people that they are "good for nothing" is not productive. Please keep your criticism constructive. This is true in any context, but especially in open-source: most of the work is volunteer driven, and the only thing that dumping on people does is cause burn-out.

**Comment by anantthebiker** [comment]
@poljar @goerz I apologise, I take my strong criticism back. It wasn’t helpful. I was stuck on trying to have OLM installed on my system, intermittently for weeks. @goerz Can I please know how did you figure out the arguments to cmake? And that it could be THE solution.

**Comment by goerz** [comment]
I just sort of guessed from what I found in the [Homebrew Formula Cookbook](https://docs.brew.sh/Formula-Cookbook) (the `*std_make_args` in particular) and what I had to do manually to get `olm` to compile. The need to replace `-Dm644` with `-m644` on macOS took a little bit of googling.

The `cmake --version` doesn't really do anything, of course, except to assure me that it's picking up the `cmake` I expect from inside homebrew. I'm not very deep into `homebrew`, so it's really just a cut-and-paste to get it to work with minimal effort (which is also why I wouldn't be comfortable to contribute the formula upstream)

**Comment by anantthebiker** [comment]
> I'm sorry you feel this way, there have been a bunch of people that asked how to install python-olm on various operating systems, I don't think I ignored any of them.
> 
> As to why there isn't a Mac specific guide, I don't use a Mac and I'm not confident enough to write a guide for an operating system I don't use and have no way to test the correctness of. If you are stuck, opening an issue or asking in the matrix-nio room might have been fruitful.
> 
> Is there anything more concrete about what's wrong with matrix-nio? API design input is always welcome, though we're a bit stuck with some decisions since we don't want to break absolutely everything.
> 
> If so, please feel free to open bug reports, suggestions and even PRs on the matrix-nio github.
> 
> Thanks, Damir.

Hey Damin @poljar , 
Seeing your name almost everywhere where matrix-nio is there, I believe you have done an incredible contribution and I also agree the documentation is tremendous for each API in Matrix-nio. 
But when it comes to some advanced use cases like: 
1) How to send an image as a message via Matrix-nio. 
2) Your GIT page says, install OLM on various platforms esp MAC(pretty common in dev community), tbh it is a struggle to figure out how to do that, may be it is deliberate on part of Matrix, that they have provided robust HowTo guides for their Synapse, but for OLM I couldn't find one. 

FYI, I have figured out the sol to the above use cases from earlier chats in Matrix-nio on Riot or from this open issue or from Testcases in the Matrix-nio git repo. I will post a guide on the solutions to above on my GIT probably or any other better place if you can suggest @poljar . 

I know you always help people on Riot, if you are the one who has written those test cases, the documentation of Matrix-Nio and OLM-python plugin. If you can post a HowTo guide on some of the challenging use cases that can be tackled with Matrix-nio it would be another great contribution. If you need some help, I am also ready to contribute. If tomorrow for a few days, you or everyone who has worked on Matri-nio go on to working somewhere else. This great project might hang in limbo like many other projects like #Hubframework . I have seen myself on RiotChat how much others struggle on using Matrix-nio. 

Looking forward to diving more deep in Matrix-nio.  

Thanks @poljar , @ara4n.

**Comment by ara4n** [comment]
I'm a bit confused by this bug - I use a Mac, and I build olm by just checking it out and running `make`, as per the instructions at https://gitlab.matrix.org/matrix-org/olm/-/blob/master/README.md#building.  There was a quirk in the Makefile which impacted macOS but this got fixed at https://gitlab.matrix.org/matrix-org/olm/-/commit/5a9fdd85cb1ad54813df2ecd6eb24ff84e32656a (and only impacted installing the library, not building it).

Separately I think I saw @aaronraimist also doing a brew for olm?

Eitherway, having a brew would be great - has one actually been submitted to homebrew?

**Comment by anantthebiker** [comment]
Hi @ara4n , just now I did a fresh clone of OLM into my Mac to test the new commit you mentioned in your comment. Then I performed: "make" -> cd python -> "make". 
Then I went into my Python project running in a separate directory with a virtual env. turned on. I tried installing the package: "matrix-nio[e2e]" using pip. I get the following error: 

   

 Running setup.py install for python-olm ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/anantpathak/Learning/ProjectSecretCam/ThePrivateSecurityCamMatrixClient/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/61/7s1yb93d42l045r0cqwms94w0000gn/T/pip-install-d5kib2sc/python-olm/setup.py'"'"'; __file__='"'"'/private/var/folders/61/7s1yb93d42l045r0cqwms94w0000gn/T/pip-install-d5kib2sc/python-olm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/61/7s1yb93d42l045r0cqwms94w0000gn/T/pip-record-htsszncy/install-record.txt --single-version-externally-managed --compile --install-headers /Users/anantpathak/Learning/ProjectSecretCam/ThePrivateSecurityCamMatrixClient/venv/include/site/python3.7/python-olm
         cwd: /private/var/folders/61/7s1yb93d42l045r0cqwms94w0000gn/T/pip-install-d5kib2sc/python-olm/
    Complete output (29 lines):
    make: *** No rule to make target `../include/olm/olm.h', needed by `include/olm/olm.h'.  Stop.
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-3.7
    creating build/lib.macosx-10.15-x86_64-3.7/olm
    copying olm/sas.py -> build/lib.macosx-10.15-x86_64-3.7/olm
    copying olm/_finalize.py -> build/lib.macosx-10.15-x86_64-3.7/olm
    copying olm/utility.py -> build/lib.macosx-10.15-x86_64-3.7/olm
    copying olm/session.py -> build/lib.macosx-10.15-x86_64-3.7/olm
    copying olm/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/olm
    copying olm/__version__.py -> build/lib.macosx-10.15-x86_64-3.7/olm
    copying olm/group_session.py -> build/lib.macosx-10.15-x86_64-3.7/olm
    copying olm/pk.py -> build/lib.macosx-10.15-x86_64-3.7/olm
    copying olm/_compat.py -> build/lib.macosx-10.15-x86_64-3.7/olm
    copying olm/account.py -> build/lib.macosx-10.15-x86_64-3.7/olm
    running build_ext
    generating cffi module 'build/temp.macosx-10.15-x86_64-3.7/_libolm.c'
    creating build/temp.macosx-10.15-x86_64-3.7
    building '_libolm' extension
    creating build/temp.macosx-10.15-x86_64-3.7/build
    creating build/temp.macosx-10.15-x86_64-3.7/build/temp.macosx-10.15-x86_64-3.7
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/anantpathak/Learning/ProjectSecretCam/ThePrivateSecurityCamMatrixClient/venv/include -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c build/temp.macosx-10.15-x86_64-3.7/_libolm.c -o build/temp.macosx-10.15-x86_64-3.7/build/temp.macosx-10.15-x86_64-3.7/_libolm.o -I../include
    build/temp.macosx-10.15-x86_64-3.7/_libolm.c:541:18: fatal error: 'olm/olm.h' file not found
            #include <olm/olm.h>
                     ^~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/anantpathak/Learning/ProjectSecretCam/ThePrivateSecurityCamMatrixClient/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/61/7s1yb93d42l045r0cqwms94w0000gn/T/pip-install-d5kib2sc/python-olm/setup.py'"'"'; __file__='"'"'/private/var/folders/61/7s1yb93d42l045r0cqwms94w0000gn/T/pip-install-d5kib2sc/python-olm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/61/7s1yb93d42l045r0cqwms94w0000gn/T/pip-record-htsszncy/install-record.txt --single-version-externally-managed --compile --install-headers /Users/anantpathak/Learning/ProjectSecretCam/ThePrivateSecurityCamMatrixClient/venv/include/site/python3.7/python-olm Check the logs for full command output.

But when I run the above brew script by creating a local tap. I am able to perfectly install "matrix-new[e2e]" . So, when following the steps mentioned in OLM's page, did I miss something for the installation of "matrix-new[e2e]"? 

Thanks, 
Anant

**Comment by aaronraimist** [comment]
Olm is in Homebrew. All you need to do is `brew install libolm.

**Comment by poljar** [comment]
>     1. How to send an image as a message via Matrix-nio.

We just got an example committed to the nio repo on how to do this, you can find it [here](https://matrix-nio.readthedocs.io/en/latest/nio.html#nio.AsyncClient.upload). Note, that this requires matrix-nio from master.

>     2. Your GIT page says, install OLM on various platforms esp MAC(pretty common in dev community), tbh it is a struggle to figure out how to do that, may be it is deliberate on part of Matrix, that they have provided robust HowTo guides for their Synapse, but for OLM I couldn't find one.

I think this is solved since libolm is in Homebrew.

> FYI, I have figured out the sol to the above use cases from earlier chats in Matrix-nio on Riot or from this open issue or from Testcases in the Matrix-nio git repo. I will post a guide on the solutions to above on my GIT probably or any other better place if you can suggest @poljar .

Contributions to the matrix-nio repo are always welcome.

If you have any further questions about matrix-nio feel free to open issues on the project repo or ask in the matrix-nio room.

**Comment by uhoreg** [comment]
Since libolm is now in homebrew (thanks, Aaron!), I'm going to close this issue.

**Comment by shehackedyou** [comment]
> I'm a bit confused by this bug - I use a Mac, and I build olm by just checking it out and running `make`, as per the instructions at https://gitlab.matrix.org/matrix-org/olm/-/blob/master/README.md#building. There was a quirk in the Makefile which impacted macOS but this got fixed at https://gitlab.matrix.org/matrix-org/olm/-/commit/5a9fdd85cb1ad54813df2ecd6eb24ff84e32656a (and only impacted installing the library, not building it).
> 
> Separately I think I saw @aaronraimist also doing a brew for olm?
> 
> Eitherway, having a brew would be great - has one actually been submitted to homebrew?

I followed the steps on the page, they did not work. 

So I just built it with `make` and it worked. And now I have to remove the excess python dependencies. Itd be nice if someone could update that README

Apparently `make` is being deprecated for `cmake` 

And yes, I installed it via `brew` and that also didn't work. So it exists but unfortunately does not work. 

This is currently with the newest version Sonoma on Macbook Pro M1.

**Comment by cyb3rko** [comment]
@shehackedyou I have built the binary on MacOS. I am wondering how to use it now.  
The mautrix library depends on it and still says 'fatal error: `olm/olm.h` file not found'.

It's my first time using it

**Comment by fmt** [comment]
Brew on macos says Warning: libolm has been deprecated because it is deprecated upstream! It will be disabled on 2025-08-01.

**Comment by t3chguy** [comment]
@fmt as stated on https://gitlab.matrix.org/matrix-org/olm#important-libolm-is-now-deprecated
