### ISSUE TITLE
lobal.Olm.Account is not a constructor

### ISSUE THREAD

**Issue by drale2k** [matrix-org/olm#31]
I get the following error when trying to include `Olm.js`

```
Uncaught (in promise) TypeError: global.Olm.Account is not a constructor
    at OlmDevice._callee$ (OlmDevice.js:134)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at OlmDevice.init (asyncToGenerator.js:21)
    at Crypto._callee2$ (index.js:271)
```

I have included the latest Olm.js (3.1.4) via a script tag. The global `Olm` object is present, but there is no exposed `Account` property or method on it. Same happens if i include Olm via yarn and a require() call.

I already posted the issue on the matrix-js-sdk repo but only later i found this `olm` repository - sorry. https://github.com/matrix-org/matrix-js-sdk/issues/1374

**Comment by cbaykam** [comment]
I got the exact same issue.

**Comment by uhoreg** [comment]
You need to call `Olm.init()`, which returns a promise, and then wait for the promise to resolve.

**Comment by drale2k** [comment]
Thanks, calling `client.initCrypto()` first and then `Olm.init().then(...)` fixed the issue. Is this anywhere documented? I am pretty sure i read all possible documentation before,

**Comment by uhoreg** [comment]
Our documentation is pretty bad, so it's probably not documented anywhere.  I'll throw a quick note in the README.md in the javascript directory for the next release.
