### ISSUE TITLE
Upstream dart-olm

### ISSUE THREAD

**Issue by lukaslihotzki** [matrix-org/olm#33]
Are you interested in upstreaming my [dart-olm](https://gitlab.com/famedly/libraries/dart-olm) bindings? They are used in [Fluffy Chat](https://christianpauly.gitlab.io/fluffychat-website) for its E2EE. They support [Dart on Native and JS](https://famedly.gitlab.io/libraries/dart-olm). We would agree to relicense the bindings to Apache.

**Comment by uhoreg** [comment]
Thanks for the offer.  We don't really have the ability to maintain them as part of the olm library, though.  (For example, we don't have anybody that knows dart.)  So it's probably best to keep it separate for now.  We should probably consider making a list of known bindings somewhere, to help people find them.

**Comment by lukaslihotzki** [comment]
The list of known bindings is at https://gitlab.matrix.org/matrix-org/olm/-/blob/master/README.md#bindings
