### ISSUE TITLE
Building the Python bindings fail to bind just build libolm

### ISSUE THREAD

**Issue by PureTryOut** [matrix-org/olm#35]
I'm currently trying to update the olm package for Alpine Linux to build Python bindings as well.

I'm building Olm as suggested in the README:
```
cmake -B build \
	-DCMAKE_BUILD_TYPE=None \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib
cmake --build build

# Build Python bindings
cd python
make olm-python3
```

However, this causes the following when actually building the bindings:
```
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lolm
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
```

I see the same build commands work fine for the Arch Linux package so I'm not sure what's up here.

**Comment by uhoreg** [comment]
It looks like cmake is putting the `.so` files in `build/lib` rather than `build`, because you're passing `-DCMAKE_INSTALL_LIBDIR=lib`.  I'm not entirely sure what's the best thing to do.  Maybe you can patch `python/olm_build.py` for the Alpine package to search use `-L../build/lib` instead of `-L../build`.

**Comment by kp9001** [comment]
Did you ever figure this out? I'm attempting to build it right now and I'm running into the exact same problem. I'm running debian 10. 

``` 
.../anaconda3/compiler_compat/ld: cannot find -lolm 
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1 
```

**Comment by PureTryOut** [comment]
Not personally, but one of the other Alpine contributors did https://git.alpinelinux.org/aports/tree/community/olm/APKBUILD#n34

```
build() {
	cmake -B build \
		-DCMAKE_BUILD_TYPE=None \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
	cmake --build build

	# hack to make the python build work
	ln -s lib/libolm.so build/libolm.so
	make -C python olm-python3
}

check() {
	cd "$builddir"/build/tests
	CTEST_OUTPUT_ON_FAILURE=TRUE ctest

	cd "$builddir"/python
	# the tests also have trouble with lib path
	# give the ffi it just built with a link,
	# and the C libolm with the ld environment variable
	ln build/lib.linux-*/_libolm*.so tests/_libolm.so
	LD_LIBRARY_PATH="$builddir/build/lib" PYTHONPATH="$PWD" pytest
}

package() {
	DESTDIR="$pkgdir" cmake --build build --target install
}

py3() {
	depends="python3 py3-future py3-cffi"
	DESTDIR="$subpkgdir" make -C "$builddir"/python install-python3
}
```

**Comment by uhoreg** [comment]
This issue should be fixed in 3.2.2 (will be tagged soon), and previous hacks to work around the issue may break.

**Comment by PureTryOut** [comment]
Thanks, it builds indeed! However, I'm unsure how to run the Python tests now.

```sh
cd "$builddir"/python
PYTHONPATH="$PWD/build/lib" pytest
```

Doing this it fails to find `olm`.

```
ImportError while importing test module '/home/bart/Documents/Git/alpine/aports/community/olm/src/olm-3.2.2/python/tests/utils_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/utils_test.py:6: in <module>
    from olm import sha256
E   ModuleNotFoundError: No module named 'olm'
```

**Comment by uhoreg** [comment]
I'm going to close this issue since the original problem is fixed.  If you're still having problems running the tests, please open a new issue.  But the `python/Makefile` has a `test` target that calls `setup.py` to install in a temporary directory first and then runs the test.

**Comment by PureTryOut** [comment]
I personally set `PYTHONPATH` to the directory where `setup.py` installed it too, that works for other Python packages at least. No dice here though...
