### ISSUE TITLE
Megolm formulas in docs are somewhat broken

### ISSUE THREAD

**Issue by ksa-real** [matrix-org/olm#38]
In a bunch of places 2-digit powers overflow due to missing curly brackets. For example ![](https://latex.codecogs.com/svg.latex?y^{24}) is visible as ![](https://latex.codecogs.com/svg.latex?y^24).
![image](https://user-images.githubusercontent.com/8188774/92391305-41250e00-f0d1-11ea-9052-4feb1dbdd4b7.png)

**Comment by uhoreg** [comment]
Thanks for reporting the issue.  This is now fixed.
