### ISSUE TITLE
olm_sas_generate_bytes doesn't fail if their key is not set

### ISSUE THREAD

**Issue by saghul** [matrix-org/olm#39]
**Describe the bug**

It's possible to call `olm_sas_generate_bytes` via the JS wrapper without an error without setting the other public key

**To Reproduce**

```
var alice = new Olm.SAS();
undefined
alice.generate_bytes('SAS', 5);
Uint8Array(5) [208, 166, 111, 167, 184]
```

**Expected behavior**

Probably an error to be thrown.

**Additional context**

The Python implementation safeguards this, and an exception is thrown. In addition, having a way to know if the key was set or not might be desirable. The Python implementation does have this, too.

I'd be happy to work on a patch if we agree on a way forward.

**Comment by poljar** [comment]
At least to me this sounds like a very good idea, well I implemented the Python side so no surprise there.

It can also be added without breaking compatibility so I don't think there are any downsides to this.

But let's wait for @uhoreg to see what he thinks.

**Comment by uhoreg** [comment]
That sounds like a good idea.  It probably makes sense to implement this on the C side so that it's consistent across all the bindings.

I'm planning on making a release of olm soon.  If you can get it done quickly, go ahead.  Otherwise, I can fix it.

I think we can either add an extra field to the `OlmSAS` struct that indicates whether the key is set, or else initialize the `secret` field to all 0s, and throw an error if you try to generate bytes when `secret` is 0.

**Comment by saghul** [comment]
I'll see if I can get it done today.

**Comment by saghul** [comment]
Here you go! https://gist.github.com/saghul/82c18657f92d24f7d59ee7c245c7f30c

Tests seem to be happy:

~~~
$ npm run test

> olm@3.1.5 test /Users/saghul/work/jitsi/olm/javascript
> jasmine-node test --verbose --junitreport --captureExceptions

creating junit xml report save path: ./reports/
têst1 -> { plaintext: 'têst1', message_index: 0 }
hot beverage: ☕ -> { plaintext: 'hot beverage: ☕', message_index: 1 }
☕ -> { plaintext: '☕', message_index: 2 }
têst1 -> têst1
hot beverage: ☕ -> hot beverage: ☕
têst1 -> têst1
hot beverage: ☕ -> hot beverage: ☕
têst1 -> têst1

megolm - 30 ms
    should encrypt and decrypt - 28 ms

olm - 21 ms
    should encrypt and decrypt - 21 ms

pk - 53 ms
    should import & export keys from private parts - 14 ms
    should encrypt and decrypt - 14 ms
    should pickle and unpickle - 14 ms
    should sign and verify - 11 ms

sas - 40 ms
    should create matching SAS bytes - 14 ms
    should create matching MACs - 14 ms
    should fail to generate bytes if their key is not set - 12 ms

Finished in 0.147 seconds
9 tests, 23 assertions, 0 failures, 0 skipped
~~~

**Comment by uhoreg** [comment]
Thanks for the patch.  I've merged it now.

@poljar I guess the checks in the Python SDK can be removed now that it's done at the C level.  Is it fine to just remove the `@other_pubkey_set` annotations (and the `other_pubkey_set` function)?

**Comment by saghul** [comment]
Cheers!

**Comment by uhoreg** [comment]
This was fixed but I forgot to close it
