### ISSUE TITLE
olm.js broken with emscripten 2.0.4

### ISSUE THREAD

**Issue by lukaslihotzki** [matrix-org/olm#40]
olm.js is broken when built with emscripten 2.0.4. `Olm.init()` succeeds, but `new Olm.Account()` or other types fail with a is-not-a-function TypeError. Building with emscripten 2.0.1 works fine.

1. Download olm (I can reproduce this issue with both olm master and olm 3.1.5)
2. `make js`
3. Try to use `javascript/olm.js`, possibly with this node script in the `javascript` dir:
```
(async function() {
	var Olm = (await import('./olm.js')).default;
	await Olm.init();
	new Olm.Account();
})();
```
```
TypeError: H is not a function
    at new W (javascript/olm.js:89:187)
    at javascript/test.js:4:2
javascript/olm.js:16
```

**Comment by lukaslihotzki** [comment]
When building without `--closure 1` in `EMCC_FLAGS`, the error message improves:
```
TypeError: malloc is not a function
```

So malloc seems to be missing. Indeed, adding `"_malloc"` to `javascript/exported_functions.json` fixes this issue.

**Comment by lukaslihotzki** [comment]
This is fixed by [the fix-js branch](https://gitlab.com/famedly/libraries/olm/-/commits/fix-js/) in https://gitlab.com/famedly/libraries/olm. Please merge this (and maybe [the makefile branch](https://gitlab.com/famedly/libraries/olm/-/commits/makefile/)).

**Comment by lukaslihotzki** [comment]
There are unit tests that can be run with `npm install && node_modules/jasmine-node/bin/jasmine-node test` in the `javascript` directory. `_free` was missing too. I amended the commit in the fix-js branch.

**Comment by uhoreg** [comment]
@lukaslihotzki Thanks for finding and fixing the bug.  I'll take a look at it on Monday.

**Comment by lukaslihotzki** [comment]
Have you made some progress? Can you reproduce the issue?

**Comment by uhoreg** [comment]
Merged.  Thanks
