### ISSUE TITLE
Memory leaks in tests

### ISSUE THREAD

**Issue by lukaslihotzki** [matrix-org/olm#41]
I have run the tests (from `make test`) with valgrind memcheck and noticed some memory leaks (only in the tests). I have fixed them and added the `test_mem` target for running the tests with valgrind in [the memcheck branch](https://gitlab.com/famedly/libraries/olm/-/commits/memcheck) of https://gitlab.com/famedly/libraries/olm.

valgrind can also detect the use of uninitialized memory. It helped me testing the dart-olm bindings. Maybe it makes sense to use it for olm itself too.

**Comment by uhoreg** [comment]
Yeah, we're not too worried about memory leaks in the tests, but probably a good idea to fix it anyways.  I've merged your changes.  Thanks.
