### ISSUE TITLE
olm.js uses global variable "Module"

### ISSUE THREAD

**Issue by lukaslihotzki** [matrix-org/olm#42]
This pollutes the global object and makes olm incompatible with other libraries using the same approach, because they overwrite their Module variables. I had such a problem in [native_imaging](https://gitlab.com/famedly/libraries/native_imaging/-/tree/master/js) and solved it by opening an [IIFE](https://en.wikipedia.org/wiki/Immediately_invoked_function_expression) in the JS prefix, so that Module is defined in function scope. Then, use the Module and close and invoke the IIFE in the JS suffix. This change would not break compatibility for users of the Olm object.

Would you accept a patch?

**Comment by uhoreg** [comment]
> Would you accept a patch?

Yup, sounds good.

**Comment by lukaslihotzki** [comment]
Please merge the [iife branch](https://gitlab.com/famedly/libraries/olm/-/tree/iife) in https://gitlab.com/famedly/libraries/olm. Then, only the Olm object is globally accessible.

**Comment by uhoreg** [comment]
Merged.  Thanks
