### ISSUE TITLE
Allow access to last error code instead of error string

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/olm#45]
**Is your feature request related to a problem? Please describe.**
Currently the `olm_*_last_error` functions return a string. While that is nice to display to a user, it would be useful, if you had access to the actual enum values for comparison and type safety. As such it may be nice to provide another set of functions, maybe called `olm_*_last_error_code`, which return the error code. Of course that implies that the error enum also gets exposed and the values stay the same and don't get reordered.

**Describe alternatives you've considered**
So far we just parse the string back into an error code. While that works, it feels a bit unnecessary and wasteful. It also relies on the internal error definitions and while they are stable, they need to be updated separately.

**Comment by uhoreg** [comment]
This should be fixed in https://gitlab.matrix.org/matrix-org/olm/-/commit/7263c4221b366a9f93f4d53f7ae06e62d671ae50
