### ISSUE TITLE
Don't export symbols in `lib/crypto-algorithms`

### ISSUE THREAD

**Issue by pksadiq** [matrix-org/olm#47]
Don't export symbols in `lib/crypto-algorithms`

The functions like `aes_encrypt ()` are not declared in any public headers. And so it would be nice if they are not exported so that I can avoid conflicts when I use libraries having such symbols defined.

One if my projects (chatty) uses libolm for matrix E2EE support. But it's crashing when sending/receiving encrypted XMPP messages because of this conflict (see https://source.puri.sm/Librem5/chatty/-/issues/450)

Thanks

**Comment by pksadiq** [comment]
Or alternately - since these symbols are not public - renaming them to have `olm` namespace would also help (so something like `olm_aes_encrypt()` (or prefixed with `_olm`) and so on) would be enough.

**Comment by pksadiq** [comment]
[0001-crypto-Rename-some-aes-symbols.zip](https://github.com/matrix-org/olm/files/6082525/0001-crypto-Rename-some-aes-symbols.zip)

Here is a minimal patch that renames only the conflicting symbols. And interestingly github doesn't allow to upload `.patch` files.

**Comment by uhoreg** [comment]
This should be fixed by https://gitlab.matrix.org/matrix-org/olm/-/commit/1b7973626e27beb05a55df6085f643a1323db987
