### ISSUE TITLE
Add to list of available bindings.

### ISSUE THREAD

**Issue by K1D77A** [matrix-org/olm#48]
Hi,

Would it be possible to add https://github.com/K1D77A/cl-megolm to the list of available bindings? 
Licensed as MIT and is written in Common Lisp.

Thanks.

**Comment by uhoreg** [comment]
Done in https://gitlab.matrix.org/matrix-org/olm/-/commit/bcb89bcc243688f063a059b8fd7afd220588efd6  Thanks.
