### ISSUE TITLE
olm_sas_calculate_mac_fixed_base64 not declared in header

### ISSUE THREAD

**Issue by lukaslihotzki** [matrix-org/olm#49]
**Describe the bug**
Library users need to declare `olm_sas_calculate_mac_fixed_base64` manually, because this function isn't declared in `include/olm/sas.h`.

**Comment by uhoreg** [comment]
Fixed by https://gitlab.matrix.org/matrix-org/olm/-/commit/7f53dedca667015013bd5307b9bfc0ad9dcf127c
