### ISSUE TITLE
`olm`  fails with `wasm validation error: at offset 4: failed to match magic number`

### ISSUE THREAD

**Issue by nickx720** [matrix-org/olm#50]
### Olm JS Bug Report

Getting
```
wasm validation error: at offset 4: failed to match magic number
```

when running olm js package .

## Describe the bug

Web page displays wasm validation error: at offset 4: failed to match magic number, instead of running the actual web assembly. 

## To Reproduce
1. npm install olm js package from https://packages.matrix.org/npm/olm/
2. Initialize the olm and create an instance of Account. 
3. Call the generate_one_time_keys() method on the account insance.
4. npm run dev
4. Observe error

## Expecated Behaviour
I expected to see the result of Olm to generate a one time key.

## Screenshots
<img width="951" alt="image" src="https://user-images.githubusercontent.com/34407800/111637959-44abf700-87d0-11eb-9a6d-ca7f70c0d31e.png">

## System Information
 - MacOS Big Sur
 - Firefox 86/Safari 14/Chrome 88
 - React version 17
 - Olm package version 3.2.1

## Additional context
I followed the example given in the README.MD for the olm package.

**Comment by uhoreg** [comment]
It is probably loading the wrong file.  Can you check that it is trying to load the .wasm file from the right location?
