### ISSUE TITLE
Add license comments to JS files to prevent GNU LibreJS from blocking them

### ISSUE THREAD

**Issue by Johennes** [matrix-org/olm#52]
**Is your feature request related to a problem? Please describe.**

As described in vector-im/hydrogen-web#209, Hydrogen currently cannot be run in tandem with LibreJS. One of the problems is that `olm.js` is blocked because LibreJS cannot infer its license. This is probably a rather small use case but for those people who run LibreJS, this results in a total DOS.

**Describe the solution you'd like**

`olm.js` and `olm_legacy.js` should self-identify their licensing by wrapping their sources in

```
// @license magnet:?xt=urn:btih:8e4f440f4c65981c5bf93c76d35135ba5064d8b7&dn=apache-2.0.txt Apache-2.0
// @source: https://gitlab.matrix.org/matrix-org/olm/-/tree/[VERSION]
```
and

```
// @license-end
```

These comments could be wrapped via the `Makefile`, for instance like this (there's probably a more elegant way):

```
diff --git a/Makefile b/Makefile
index 4371c63..196d1d2 100644
--- a/Makefile
+++ b/Makefile
@@ -36,6 +36,10 @@ JS_EXPORTED_FUNCTIONS := javascript/exported_functions.json
 JS_EXTRA_EXPORTED_RUNTIME_METHODS := [ALLOC_STACK]
 JS_EXTERNS := javascript/externs.js

+JS_LICENSE_START := // @license magnet:?xt=urn:btih:8e4f440f4c65981c5bf93c76d35135ba5064d8b7&dn=apache-2.0.txt Apache-2.0
+JS_LICENSE_SOURCE := // @source: https://gitlab.matrix.org/matrix-org/olm/-/tree/$(VERSION)
+JS_LICENSE_END := // @license-end
+
 PUBLIC_HEADERS := include/olm/olm.h include/olm/outbound_group_session.h include/olm/inbound_group_session.h include/olm/pk.h include/olm/sas.h

 SOURCES := $(wildcard src/*.cpp) $(wildcard src/*.c) \
@@ -204,6 +208,8 @@ $(JS_WASM_TARGET): $(JS_OBJECTS) $(JS_PRE) $(JS_POST) $(JS_EXPORTED_FUNCTIONS) $
                -s "EXPORTED_FUNCTIONS=@$(JS_EXPORTED_FUNCTIONS)" \
                -s "EXTRA_EXPORTED_RUNTIME_METHODS=$(JS_EXTRA_EXPORTED_RUNTIME_METHODS)" \
                -o $@ $(JS_OBJECTS)
+       { echo "$(JS_LICENSE_START)"; echo "$(JS_LICENSE_SOURCE)"; echo; cat $@; echo "$(JS_LICENSE_END)"; } > $@.tmp
+       mv $@.tmp $@

 $(JS_ASMJS_TARGET): $(JS_OBJECTS) $(JS_PRE) $(JS_POST) $(JS_EXPORTED_FUNCTIONS) $(JS_PREFIX) $(JS_SUFFIX)
        EMCC_CLOSURE_ARGS="--externs $(JS_EXTERNS)" $(EMCC_LINK) \
@@ -215,6 +221,8 @@ $(JS_ASMJS_TARGET): $(JS_OBJECTS) $(JS_PRE) $(JS_POST) $(JS_EXPORTED_FUNCTIONS)
                -s "EXPORTED_FUNCTIONS=@$(JS_EXPORTED_FUNCTIONS)" \
                -s "EXTRA_EXPORTED_RUNTIME_METHODS=$(JS_EXTRA_EXPORTED_RUNTIME_METHODS)" \
                -o $@ $(JS_OBJECTS)
+       { echo "$(JS_LICENSE_START)"; echo "$(JS_LICENSE_SOURCE)"; echo; cat $@; echo "$(JS_LICENSE_END)"; } > $@.tmp
+       mv $@.tmp $@

 build_tests: $(TEST_BINARIES)
```

Happy to send the patch via email if this seems like an acceptable solution.

**Describe alternatives you've considered**

There are [different options](https://www.gnu.org/software/librejs/free-your-javascript.html) for declaring the license in a way that LibreJS understands. However, I believe the magnet comments are the most minimal approach.

It is technically also possible to declare the license on the client side. Having it in Olm itself though makes _any_ consuming client benefit from it, not just e.g. Hydrogen.

**Additional context**

Similar license comments for Hydrogen's internal JS are being added in vector-im/hydrogen-web#301.

**Comment by Johennes** [comment]
Submitted the above patch via email.

**Comment by uhoreg** [comment]
Thanks for the suggestion.  Fixed by https://gitlab.matrix.org/matrix-org/olm/-/commit/f16377822f2b3b0f00bebf244d2dfb8fb1712344
