### ISSUE TITLE
Execution failed for task ':olm-sdk:ndkBuildNativeDebug'

### ISSUE THREAD

**Issue by sourish115** [matrix-org/olm#56]
**Describe the bug**
I have followed the instruction at https://gitlab.matrix.org/matrix-org/olm/-/tree/master/android in readme.rst to install libolm in my android studio project. However I get an error during ndk-build.cmd process which says:-
    jni/Android.mk:9: jni/../../../../../common.mk: No such file or directory
    make: *** No rule to make target `jni/../../../../../common.mk'.  Stop.

**To Reproduce**
1. Create a new android studio project
2. Copy the olm-sdk.aar file into 'libs' director'
3. In project level build.gradle, add 
   flatDir {
        dir 'libs'
    }
under the repositories section in allprojects.
4. In module level build.gradle, added dependency -> implementation(name: 'olm-sdk', ext: 'aar')
5. Then from File->New->Import Module imported project from android/ path of Olm repository
6. Then from File->project Structure->dependency->add dependency->module dependency->olm-sdk
7. Make project

**Expected behavior**
Should build without any errors

**Desktop (please complete the following information):**
 - OS: Windows 10 home
 - NDK version - 20.0.5594570

**Additional context**

**Comment by uhoreg** [comment]
It looks like it's trying to rebuild the library.  Where are you getting the .aar file from?

**Comment by sourish115** [comment]
I generated the .aar after following the instructions in the GitLab repo.
I am now using the .so files to use the olm library.
In my android studio project, there are 3 modules and one module (module X)is using a native library using cmake. I'm building the library for only for 'armeabi-v7a' and 'x86' architectures.
To add the olm library, copied the .so files of olm for the required 2 architectures, along with the include directory of olm, to the jnilibs directory of my module X. After that i added it as a shared imported library using cmake in my CMakeLists.txt file

**Comment by uhoreg** [comment]
Can you try running `./gradlew clean build` instead of `./gradlew clean assembleRelease`?  Alternatively, you can use pre-built .aar files from [Maven Central](https://search.maven.org/artifact/org.matrix.android/olm-sdk)
