### ISSUE TITLE
Podfile.lock checksum problem in iOS

### ISSUE THREAD

**Issue by karol-bisztyga** [matrix-org/olm#58]
**Describe the bug**

When attaching this lib to an iOS project using `OLMKit.podspec` and sharing it with other people via some version control system, each team member has a different checksum in the `Podfile.lock` file. This is because `OLMKit.podspec` contains machine-specific paths [here](https://gitlab.matrix.org/matrix-org/olm/-/blob/master/OLMKit.podspec#L50). To overcome this I needed to do patching with relative paths. 

**To Reproduce**
1. Create an iOS project
2. Add this lib as a `pod`
3. `pod install`
4. upload to the cloud
5. download contents from the cloud on a different machine
6. `pod install` on that second machine

**Expected behavior**

The same Podfile.lock file contents on every machine.

**Comment by manuroe** [comment]
Why not using the official release with `pod 'OLMKit'` or SPM (https://gitlab.matrix.org/matrix-org/olm/-/tree/master/xcode)?

The line you are pointing is for development and when you have the repo checked out locally. We use it, for example, when working on the Matrix SDK in parallel (https://github.com/matrix-org/matrix-ios-sdk/blob/v0.19.0/Podfile#L11).

**Comment by karol-bisztyga** [comment]
Thanks for explaining!
