### ISSUE TITLE
Message Encryption

### ISSUE THREAD

**Issue by nich01as** [matrix-org/olm#60]
Hello! I'm really sorry if this question appears to be out of place but I'm not sure where it will be appropriate to raise this query and I thought I will do it here.

I simply want to replace the message encryption scheme from AES-256 CBC mode to another cryptographic scheme, keeping the Melgolm scheme unchanged. However, after reading through the huge codebase, I am rather confused as to which function to replace.

For background, I am using Element as the client and I have managed to narrow down the encryption function to 
`OLM_OUTBOUND_GROUP_SESSION_FUNC_DEF` function in  `android/olm-sdk/src/main/jni/olm_outbound_group_session.cpp`.

It seems that the message encryption is done in the following line:
```cpp
size_t encryptedLength = olm_group_encrypt(sessionPtr,
                                                       (uint8_t*)clearMsgPtr,
                                                       clearMsgLength,
                                                       encryptedMsgPtr,
                                                       encryptedMsgLength);
````
but I am unable to find where the olm_group_encrypt function is (which I believe is where I will make the modifications).

Am I on the right track? 

Thank you in advance for any help!

**Comment by uhoreg** [comment]
The code that you would need to change is probably going to be in the top-level `src` directory.  The `android` directory only  contains the bindings for Android, and won't contain any cryptographic functions.
