### ISSUE TITLE
Wrong session size in tests

### ISSUE THREAD

**Issue by karol-bisztyga** [matrix-org/olm#62]
# Describe the bug
Hey!
I spotted that you probably passed an invalid size for the session in your tests [here](https://gitlab.matrix.org/matrix-org/olm/-/blob/7dd4c77c1913b2245b0415968952938ca2e2ffc5/tests/test_olm.cpp#L200).
You use `olm_account_size` for the buffer that's later used in `olm_session`. Shouldn't it be like the following?
```cpp
std::vector<std::uint8_t> b_session_buffer(::olm_session_size());
::OlmSession *b_session = ::olm_session(b_session_buffer.data());
```
instead what's there:
```cpp
std::vector<std::uint8_t> b_session_buffer(::olm_account_size());
::OlmSession *b_session = ::olm_session(b_session_buffer.data());
```

**Comment by poljar** [comment]
This bug seems to have existed for quite a time: https://gitlab.matrix.org/matrix-org/olm/-/commit/76f49cf17780c155dd02d39ebc40e1f62c0c2503#2b5171efddf233bca5a99943ddbfc982b39f24c1_0_82.

Stuff probably works because `olm_account_size()` is bigger than `olm_session_size()`.

**Comment by karol-bisztyga** [comment]
I suppose so, still, can be misleading and if it happens to change the other direction one day, it'll break.

**Comment by poljar** [comment]
Sure, I'm not arguing that this shouldn't be fixed.

**Comment by uhoreg** [comment]
Fixed in https://gitlab.matrix.org/matrix-org/olm/-/commit/6c552dd7eb596e806b3416a4bf78186314f75d67  Thanks.
