### ISSUE TITLE
python-olm build fails with missing header 

### ISSUE THREAD

**Issue by b3n4kh** [matrix-org/olm#66]
**Describe the bug**
I built libolm from source, and install the library as well as the headers `make install-headers`.
Afters I try to build the python-olm python wheel `pip install python-olm` which fails with:

```
In file included from /usr/local/include/olm/olm.h:23,
               from build/temp.linux-x86_64-3.10/_libolm.c:570:
/usr/local/include/olm/inbound_group_session.h:23:10: fatal error: olm/olm_export.h: No such file or directory
   23 | #include "olm/olm_export.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

If I add `include/olm/olm_export.h` to the [PUBLIC_HEADERS variable in the Makefile](https://gitlab.matrix.org/matrix-org/olm/-/blob/master/Makefile#L37) the build passes as expected.

**To Reproduce**
1. `make install`
2. `make install-headers`
3. `pip install python-olm`

**Expected behavior**
`pip install python-olm` passes without an error

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 34

**Comment by uhoreg** [comment]
Thanks for reporting.  This should be fixed by https://gitlab.matrix.org/matrix-org/olm/-/commit/201f139523a6bb0a1dd85be71bec32db84e51708
