### ISSUE TITLE
Make olm compatible with Kotlin Multiplatform Mobile

### ISSUE THREAD

**Issue by jimmyneutront** [matrix-org/olm#67]
**Problem related to feature request**
I want to use the Matrix iOS SDK in an application that I am building with Kotlin Multiplatform Mobile. The Matrix iOS SDK depends on the OLMKit CocoaPod, and olm makes use of a "semantic import" statement (`@import Security`) in line 26 of `xcode/OLMKit/OLMAccount.m`. Currently, code containing "semantic import" statements is not compatible with KMM projects due to an issue with the cinterop tool, as described [here](https://youtrack.jetbrains.com/issue/KT-39120).

**Desired solution**
I would like that single use of the `@import` statement to be replaced with a traditional compiler `#import` directive.

**Alternatives Considered**
I could fork the repo and make this change myself, but then I would also have to host the resulting OLMKit CocoaPod, which would necessitate creating my own fork of MatrixSDK as well, modified to depend on my own OLMKit version. Additionally, until this fix is implemented in olm, no other KMM developers can use the Matrix iOS SDK in their projects.

**Comment by Johennes** [comment]
I sent a corresponding patch to olm@matrix.org.

**Comment by uhoreg** [comment]
Fixed by https://gitlab.matrix.org/matrix-org/olm/-/commit/bce4f007b1f0077260452912a95f0bf175e24108
