### ISSUE TITLE
libolm is exporting `lib/crypto-algorithms` again since 72b8bf533423daf6b3b5cadfc70584cefb99b0ec

### ISSUE THREAD

**Issue by pksadiq** [matrix-org/olm#69]
Hi,

  libolm fixed exporting private symbols in [1b7973626e27beb05a55df6085f643a1323db987](https://gitlab.matrix.org/matrix-org/olm/-/commit/1b7973626e27beb05a55df6085f643a1323db987) (See #47), but this issue re-appeared in [72b8bf533423daf6b3b5cadfc70584cefb99b0ec](https://gitlab.matrix.org/matrix-org/olm/-/commit/72b8bf533423daf6b3b5cadfc70584cefb99b0ec) (as per `git bisect`).

 `nm -gCD` lists `aes_..` symbols as exported resulting in a crash when the wrong symbol is used for execution

**Comment by uhoreg** [comment]
Ugh.  Sorry.  Should be fixed in https://gitlab.matrix.org/matrix-org/olm/-/commit/98b8e35a7cf71df4de100a14e30a85b9d7515a23

**Comment by pksadiq** [comment]
thanks, that was a pretty fast fix. :)
