### ISSUE TITLE
Signed preKey correspondent from SignalProtocol

### ISSUE THREAD

**Issue by clawoo** [matrix-org/olm#7]
Hello! I'm trying to get Olm to work with XMPPFramework, but I am hitting some walls here related to compatibility between the OMEMO implementation in the framework (which seems to follow SignalProtocol's lead) and Olm.

The [DoubleRatchet spec from OWS](https://whispersystems.org/docs/specifications/doubleratchet/) mentions a signed prekey that needs to be uploaded , however, in Olm 2.2.2 I was unable to find any reference to something similar. Does Olm support it? What would be its correspondent?

**Comment by itamarwe** [comment]
As far as I understand, Olm does not support the signed prekey. What is implemented in Olm is the handshake as described here: https://signal.org/blog/simplifying-otr-deniability/

If you want to implement Omemo using olm you can use stubs for the signed prekeys, and just ignore them when calling the Olm functions.

In terms of security, it means that you won't enjoy the security benefits of using signed prekeys. If you look at the list of attacks [here](https://signal.org/docs/specifications/x3dh/), you can see what attacks the signed prekeys protect you from. Personally, I think that the signed prekeys protect from relatively marginal attacks, but that depends on your own usecase and security concerns.

**Comment by richvdh** [comment]
you can sign your prekeys if you want. See https://git.matrix.org/git/olm/about/docs/signing.rst#signing-one-time-keys

**Comment by moyerr** [comment]
@richvdh What does this look like in terms of code? `OLMAccount` has a method for signing a message, but it isn't clear how one would go about signing a preKey.

**Comment by richvdh** [comment]
just sign the message you are using to distribute the prekeys. You can read about how to do iit in the Matrix protocol at https://matrix.org/docs/guides/e2e_implementation.html.
