### ISSUE TITLE
WASM runtime error `env` not found

### ISSUE THREAD

**Issue by gnunicorn** [matrix-org/olm#70]
**Describe the bug**
Building this for wasm, the resulting library enforces that all functions should be exported. Further down the compilation-tree, when linking that library in the rust-sdk for wasm, these export enforcement is kept and thus instead of 105, 203 functions are exported. As all are exported tree-shaking doesn't remove unused calls anymore, and even the `olm_session_describe` is exported, which requires `snprintf` that the wasm32 environment doesn't have. This occurred the first time in https://gitlab.matrix.org/matrix-org/olm/-/commit/72b8bf533423daf6b3b5cadfc70584cefb99b0ec .

**To Reproduce / Additional context****
https://github.com/matrix-org/matrix-rust-sdk/issues/353#issuecomment-950364363

**Fix**

The following patch uses the `OLM_STATIC_DEFINE` flag on emscripten-builds to get back to the old behaviour, where it is up to the higher library to decide which functions are exported: 
```patch
From 15ccb23b5637a09de5620e8a37441e727bb43ab3 Mon Sep 17 00:00:00 2001
From: Benjamin Kampmann <ben@gnunicorn.org>
Date: Thu, 25 Nov 2021 13:48:26 +0100
Subject: [PATCH] Disable forced exports (introduced in 72b8bf53) for wasm.

---
 Makefile | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/Makefile b/Makefile
index 1e80766..3995546 100644
--- a/Makefile
+++ b/Makefile
@@ -108,8 +108,8 @@ EMCCFLAGS_WASM += -s TOTAL_STACK=65536 -s TOTAL_MEMORY=262144
 
 EMCCFLAGS_ASMJS += -s WASM=0
 
-EMCC.c = $(EMCC) $(CFLAGS) $(CPPFLAGS) -c -DNDEBUG
-EMCC.cc = $(EMCC) $(CXXFLAGS) $(CPPFLAGS) -c -DNDEBUG
+EMCC.c = $(EMCC) $(CFLAGS) $(CPPFLAGS) -c -DNDEBUG -DOLM_STATIC_DEFINE=1
+EMCC.cc = $(EMCC) $(CXXFLAGS) $(CPPFLAGS) -c -DNDEBUG -DOLM_STATIC_DEFINE=1
 EMCC_LINK = $(EMCC) $(LDFLAGS) $(EMCCFLAGS)
 
 AFL_CC = afl-clang-fast
-- 
2.33.0

```

(I have previously emailed this patch, too. Don't mean to be pushy, just need a public record I can link to).

**Comment by uhoreg** [comment]
Patch applied in https://gitlab.matrix.org/matrix-org/olm/-/commit/f6309f0281c6c2947ccd877f50ba0aa1df2d065b  Thanks.

**Comment by DJankauskas** [comment]
I'm getting the same or similar bug, as I'm unable to compile on wasm as `malloc`, `free`, and `snprintf` are required but aren't available in the wasm environment. This is on 1.3.0 of the library.

**Comment by uhoreg** [comment]
libolm doesn't make any calls to `malloc` or `free`.  Also, version 1.3.0 of the library is ancient.  I'm assuming you meant some other version.  Version 3.2.7 is the first version with the fix above.

**Comment by gnunicorn** [comment]
@DJankauskas  we've noticed [this only works with emscripten 2.0.17 reliably](https://github.com/matrix-org/matrix-rust-sdk/pull/414/commits/9ff4609f3dae2c8707e871d20e1a5c37ece0822f#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR182), with this patch though.
