### ISSUE TITLE
NodeJS module uses deprecated test tool jasmine-node

### ISSUE THREAD

**Issue by jonassmedegaard** [matrix-org/olm#71]
The NodeJS wrapper for libolm uses https://github.com/mhevery/jasmine-node for testing.
That tool declares this:
> This project is now in maintenance mode. It is recommended to use the jasmine or jasmine-npm package whenever possible.

It would be helpful if testsuite could be adapted to use actively maintained jasmine instead.

**Comment by uhoreg** [comment]
Thanks for the report.  This is now done in https://gitlab.matrix.org/matrix-org/olm/-/commit/60122a2c2d68c9b04f2a95d2b06ef9fae546f247
