### ISSUE TITLE
How to Sign Up in Matrix' Gitlab?

### ISSUE THREAD

**Issue by elibroftw** [matrix-org/olm#73]
![image](https://user-images.githubusercontent.com/21298211/146483296-790e826c-dfc7-436b-ba5e-3a46a772d6ad.png)

**Comment by richvdh** [comment]
I'm afraid our gitlab instance is not open for public registration.

**Comment by uhoreg** [comment]
If you want to submit patches, please email them to `olm@matrix.org` (and read https://gitlab.matrix.org/matrix-org/olm/-/blob/master/CONTRIBUTING.md).

**Comment by elibroftw** [comment]
I'm thankful you guys are on here though. My question is can you guys add olm to the vcpkg repository? Maybe then the Python-olm build will work...
