### ISSUE TITLE
Unable to install matrix-nio on MacOS

### ISSUE THREAD

**Issue by tedwardd** [matrix-org/olm#74]
**Describe the bug**
On MacOS 11.6 (20G165) it seems that installing python-olm via homebrew is no longer sufficient to allow `matrix-nio[e2e]>=0.18.7` to install successfully. It appears there may be a linking issue but I don't fully understand what's going on here.

**To Reproduce**
1. `virtualenv ~/.weechat/python/venv`
2. `. ~/.weechat/python/venv/bin/activate`
3.`brew install libolm`
4. `cd weechat-matrix`
5. `pip install -r requirements.txt`

**Expected behavior**
`pip install -r requirements.txt` should install all packages without error after following the documented setup steps for MacOS.

**Screenshots**
<details>
<summary>Click to expand the full output from `pip install -r requirements.txt`</summary>
<pre>
Ignoring typing: markers 'python_version < "3.5"' don't match your environment
Ignoring future: markers 'python_version < "3.2"' don't match your environment
Requirement already satisfied: pyOpenSSL in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (21.0.0)
Requirement already satisfied: webcolors in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.11.1)
Requirement already satisfied: atomicwrites in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: attrs in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (21.3.0)
Requirement already satisfied: logbook in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (1.5.3)
Requirement already satisfied: pygments in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (2.10.0)
Collecting matrix-nio[e2e]>=0.18.7
  Using cached https://artifactory.rsglab.com/artifactory/api/pypi/pypi/packages/packages/d6/0f/58d984640bbfd0001845e5611318dc56c8346d2324c4117c04a39ffe0c15/matrix_nio-0.18.7-py3-none-any.whl (183 kB)
Requirement already satisfied: aiohttp in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (3.8.1)
Requirement already satisfied: python-magic in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (0.4.24)
Requirement already satisfied: requests in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (2.26.0)
Requirement already satisfied: cryptography>=3.3 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from pyOpenSSL->-r requirements.txt (line 1)) (36.0.1)
Requirement already satisfied: six>=1.5.2 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from pyOpenSSL->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: jsonschema<4.0.0,>=3.2.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (3.2.0)
Requirement already satisfied: h11<0.13.0,>=0.12.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (0.12.0)
Requirement already satisfied: aiohttp-socks<0.7.0,>=0.6.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (0.6.1)
Requirement already satisfied: aiofiles<0.7.0,>=0.6.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (0.6.0)
Requirement already satisfied: h2<5.0.0,>=4.0.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (4.1.0)
Requirement already satisfied: future<0.19.0,>=0.18.2 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (0.18.2)
Requirement already satisfied: pycryptodome<4.0.0,>=3.10.1 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (3.12.0)
Requirement already satisfied: unpaddedbase64<3.0.0,>=2.1.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (2.1.0)
Collecting cachetools<5.0.0,>=4.2.1
  Using cached https://artifactory.rsglab.com/artifactory/api/pypi/pypi/packages/packages/ea/c1/4740af52db75e6dbdd57fc7e9478439815bbac549c1c05881be27d19a17d/cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting peewee<4.0.0,>=3.14.4
  Using cached peewee-3.14.8-cp310-cp310-macosx_11_0_x86_64.whl
Collecting python-olm<4.0.0,>=3.1.3
  Using cached https://artifactory.rsglab.com/artifactory/api/pypi/pypi/packages/packages/d4/a4/1face47e65118d7c52726dfa305410a96bc4a0c6f3f99c90bc7104aebf21/python-olm-3.1.3.tar.gz (27 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: frozenlist>=1.1.1 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 10)) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 10)) (1.7.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 10)) (2.0.9)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 10)) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 10)) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 10)) (5.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from requests->-r requirements.txt (line 12)) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from requests->-r requirements.txt (line 12)) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from requests->-r requirements.txt (line 12)) (3.3)
Requirement already satisfied: python-socks[asyncio]<2.0.0,>=1.2.4 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from aiohttp-socks<0.7.0,>=0.6.0->matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (1.2.4)
Requirement already satisfied: cffi>=1.12 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from cryptography>=3.3->pyOpenSSL->-r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: hpack<5,>=4.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from h2<5.0.0,>=4.0.0->matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (4.0.0)
Requirement already satisfied: hyperframe<7,>=6.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from h2<5.0.0,>=4.0.0->matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (6.0.1)
Requirement already satisfied: setuptools in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from jsonschema<4.0.0,>=3.2.0->matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (60.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from jsonschema<4.0.0,>=3.2.0->matrix-nio[e2e]>=0.18.7->-r requirements.txt (line 9)) (0.18.0)
Requirement already satisfied: pycparser in /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=3.3->pyOpenSSL->-r requirements.txt (line 1)) (2.21)
Building wheels for collected packages: python-olm
  Building wheel for python-olm (setup.py): started
  Building wheel for python-olm (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /Users/tedwood/.weechat/python/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-install-ph2jmwyf/python-olm_ad138159c23641cc99fac48b8d3c152e/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-install-ph2jmwyf/python-olm_ad138159c23641cc99fac48b8d3c152e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-wheel-9zf73oup
       cwd: /private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-install-ph2jmwyf/python-olm_ad138159c23641cc99fac48b8d3c152e/
  Complete output (27 lines):
  make: *** No rule to make target `../include/olm/olm.h', needed by `include/olm/olm.h'.  Stop.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11-x86_64-3.10
  creating build/lib.macosx-11-x86_64-3.10/olm
  copying olm/sas.py -> build/lib.macosx-11-x86_64-3.10/olm
  copying olm/_finalize.py -> build/lib.macosx-11-x86_64-3.10/olm
  copying olm/utility.py -> build/lib.macosx-11-x86_64-3.10/olm
  copying olm/session.py -> build/lib.macosx-11-x86_64-3.10/olm
  copying olm/__init__.py -> build/lib.macosx-11-x86_64-3.10/olm
  copying olm/__version__.py -> build/lib.macosx-11-x86_64-3.10/olm
  copying olm/group_session.py -> build/lib.macosx-11-x86_64-3.10/olm
  copying olm/pk.py -> build/lib.macosx-11-x86_64-3.10/olm
  copying olm/_compat.py -> build/lib.macosx-11-x86_64-3.10/olm
  copying olm/account.py -> build/lib.macosx-11-x86_64-3.10/olm
  running build_ext
  creating build/temp.macosx-11-x86_64-3.10
  creating build/temp.macosx-11-x86_64-3.10/build
  creating build/temp.macosx-11-x86_64-3.10/build/temp.macosx-11-x86_64-3.10
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/Users/tedwood/.weechat/python/venv/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c build/temp.macosx-11-x86_64-3.10/_libolm.c -o build/temp.macosx-11-x86_64-3.10/build/temp.macosx-11-x86_64-3.10/_libolm.o -I../include
  clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk build/temp.macosx-11-x86_64-3.10/build/temp.macosx-11-x86_64-3.10/_libolm.o -lolm -o build/lib.macosx-11-x86_64-3.10/_libolm.abi3.so -L../build
  ld: warning: directory not found for option '-L../build'
  ld: library not found for -lolm
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for python-olm
  Running setup.py clean for python-olm
Failed to build python-olm
Installing collected packages: python-olm, peewee, matrix-nio, cachetools
    Running setup.py install for python-olm: started
    Running setup.py install for python-olm: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/tedwood/.weechat/python/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-install-ph2jmwyf/python-olm_ad138159c23641cc99fac48b8d3c152e/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-install-ph2jmwyf/python-olm_ad138159c23641cc99fac48b8d3c152e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-record-x3jh6r7s/install-record.txt --single-version-externally-managed --compile --install-headers /Users/tedwood/.weechat/python/venv/include/site/python3.10/python-olm
         cwd: /private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-install-ph2jmwyf/python-olm_ad138159c23641cc99fac48b8d3c152e/
    Complete output (29 lines):
    make: *** No rule to make target `../include/olm/olm.h', needed by `include/olm/olm.h'.  Stop.
    running install
    /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib.macosx-11-x86_64-3.10
    creating build/lib.macosx-11-x86_64-3.10/olm
    copying olm/sas.py -> build/lib.macosx-11-x86_64-3.10/olm
    copying olm/_finalize.py -> build/lib.macosx-11-x86_64-3.10/olm
    copying olm/utility.py -> build/lib.macosx-11-x86_64-3.10/olm
    copying olm/session.py -> build/lib.macosx-11-x86_64-3.10/olm
    copying olm/__init__.py -> build/lib.macosx-11-x86_64-3.10/olm
    copying olm/__version__.py -> build/lib.macosx-11-x86_64-3.10/olm
    copying olm/group_session.py -> build/lib.macosx-11-x86_64-3.10/olm
    copying olm/pk.py -> build/lib.macosx-11-x86_64-3.10/olm
    copying olm/_compat.py -> build/lib.macosx-11-x86_64-3.10/olm
    copying olm/account.py -> build/lib.macosx-11-x86_64-3.10/olm
    running build_ext
    creating build/temp.macosx-11-x86_64-3.10
    creating build/temp.macosx-11-x86_64-3.10/build
    creating build/temp.macosx-11-x86_64-3.10/build/temp.macosx-11-x86_64-3.10
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/Users/tedwood/.weechat/python/venv/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c build/temp.macosx-11-x86_64-3.10/_libolm.c -o build/temp.macosx-11-x86_64-3.10/build/temp.macosx-11-x86_64-3.10/_libolm.o -I../include
    clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk build/temp.macosx-11-x86_64-3.10/build/temp.macosx-11-x86_64-3.10/_libolm.o -lolm -o build/lib.macosx-11-x86_64-3.10/_libolm.abi3.so -L../build
    ld: warning: directory not found for option '-L../build'
    ld: library not found for -lolm
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/tedwood/.weechat/python/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-install-ph2jmwyf/python-olm_ad138159c23641cc99fac48b8d3c152e/setup.py'"'"'; __file__='"'"'/private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-install-ph2jmwyf/python-olm_ad138159c23641cc99fac48b8d3c152e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c5/j8r6cdw10j73kjt5jv3cljk40000gq/T/pip-record-x3jh6r7s/install-record.txt --single-version-externally-managed --compile --install-headers /Users/tedwood/.weechat/python/venv/include/site/python3.10/python-olm Check the logs for full command output.
</pre>
</details>

**Additional context**
```
$ python --version
Python 3.10.1
```

```
$ pip --version
pip 21.3.1 from /Users/tedwood/.weechat/python/venv/lib/python3.10/site-packages/pip (python 3.10)
```

```
$ brew info libolm
libolm: stable 3.2.8 (bottled)
Implementation of the Double Ratchet cryptographic ratchet
https://gitlab.matrix.org/matrix-org/olm
/usr/local/Cellar/libolm/3.2.8 (19 files, 265.5KB) *
  Poured from bottle on 2021-12-28 at 11:30:23
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libolm.rb
License: Apache-2.0
==> Dependencies
Build: cmake ✔
==> Analytics
install: 239 (30 days), 446 (90 days), 1,445 (365 days)
install-on-request: 219 (30 days), 412 (90 days), 1,310 (365 days)
build-error: 0 (30 days)
```

```
$ brew list | grep libolm
libolm
```

**Comment by uhoreg** [comment]
The latest [README](https://gitlab.matrix.org/matrix-org/olm#macos) has instructions for how to install the Python package on macos:

```
pip install python-olm --global-option="build_ext" --global-option="--include-dirs="`brew --prefix libolm`"/include" --global-option="--library-dirs="`brew --prefix libolm`"/lib"
```

 Can you give that a try?

**Comment by uhoreg** [comment]
The latest python-olm package should be installable on macOS with cmake and a C/C++ compiler without any extra options.
