### ISSUE TITLE
make target doc fails (sources expected to be ReST but are mostly Markdown)

### ISSUE THREAD

**Issue by jonassmedegaard** [matrix-org/olm#75]
This (in source) fails:
```shell
make doc
```

The Cmake build system apparently do not handle documentation at all.

This was fixed in Debian [like this](https://salsa.debian.org/matrix-team/olm/-/blob/debian/latest/debian/patches/1001_fix_make_doc.patch):
```patch
--- a/Makefile
+++ b/Makefile
@@ -401,6 +401,9 @@
 %.html: %.rst
 	rst2html $< $@
 
+%.html: %.md
+	markdown-it $< > $@
+
 ### dependencies
 
 -include $(RELEASE_OBJECTS:.o=.d)
```

**Comment by uhoreg** [comment]
Does `markdown-it` produce reasonable results for the math in the docs?

**Comment by jonassmedegaard** [comment]
Quoting Hubert Chathi (2022-01-13 17:26:30)
> Does `markdown-it` produce reasonable results for the math in the docs?

Ahh, so _that_ is what the comment "when rendering properly" hinted at.

Patch now updated to instead use pandoc with a filter, which works.  
Thanks for pointing that out!

(does not work in Debian yet, though: fixing this revealed bugs in both 
pandoc on locating system-shared katex, and in libjs-katex providing 
compacted JavaScript - the former is fixed in Debian unstable since a 
few hours, the latter I will work on tomorrow).


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by uhoreg** [comment]
Thanks.  Fixed in https://gitlab.matrix.org/matrix-org/olm/-/commit/dd1905454b033fcc1fe5e4b39dbcdac9ce82c68b
