### ISSUE TITLE
Allow growing memory for wasm

### ISSUE THREAD

**Issue by benkuly** [matrix-org/olm#76]
**Is your feature request related to a problem? Please describe.**
The memory usage of olm wasm is limited at the moment (https://gitlab.matrix.org/matrix-org/olm/-/blob/master/Makefile#L99). This limit is reached fast, when used with a client, which supports multiple accounts or when having complex unit or integration tests.

**Describe the solution you'd like**
Allow growing memory with `-sALLOW_MEMORY_GROWTH`

**Comment by uhoreg** [comment]
Thanks for the suggestion.  This is now done in https://gitlab.matrix.org/matrix-org/olm/-/commit/84807125c086f89e7b6954dbc3ccba15f41026db
