### ISSUE TITLE
Cannot assign to "process" because it's an import from an injected file

### ISSUE THREAD

**Issue by ghost** [matrix-org/olm#79]
I get 
```
X [ERROR] Cannot assign to "process" because it's an import from an injected file

    node_modules/olm/olm.js:15:292:
      15 │ ...ypto");g=function(b){var c=ba.randomBytes(b.length);b.set(c)};process=global.process}else throw Error("Cannot find global to attach...
         ╵                                                                  ~~~~~~~

  The symbol "process" was exported from
  "node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js" here:

    node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js:205:11:
      205 │ export var process = {
          ╵            ~~~~~~~
```
 after doing 
```js
import * as olm from 'olm';
global.Olm = olm;
```

This is a vite build environment with node dependencies polyfilled

**Comment by ghost** [comment]
Solved it temporarily by removing `process=global.process` and changing all calls to the `process` variable to `global.process` in olm.js

This works for now but there should be a better solution

**Comment by cesar-cardinale** [comment]
I have the same problem, how did you fixed it not temporarily ?

Thanks

**Comment by uhoreg** [comment]
If it's running `process=global.process`, that means that `typeof window` is `undefined`, which seems strange.  I don't really know anything about vite, but is there something we can use to detect that it's being used?

**Comment by cesar-cardinale** [comment]
Find a solution by adding those settings in the vite.config.ts : 
```ts
{
define: {
        global: 'window
},
optimizeDeps: {
        include: [
            '@matrix-org/olm',
        ],
        esbuildOptions: {
            define: {
                global: 'globalThis'
            },
        }
    },
}
```

**Comment by uhoreg** [comment]
I've removed the offending line: https://gitlab.matrix.org/matrix-org/olm/-/commit/8f4b81b512702871df7cced8397e71b8529a1251 Looking through the git history, it looks like that line was added as a workaround for Closure Compiler but is no longer needed.
