### ISSUE TITLE
ImportError: libolm.so.3 (Failed Python OLM Installation)

### ISSUE THREAD

**Issue by Giffari17** [matrix-org/olm#80]
I tried to install python-olm 3 in my python venv,
1. I entered my venv
2. I followed the instructions from: https://gitlab.matrix.org/matrix-org/olm/tree/master/ (to build olm)
3. I go to python dir in that repo, i did: (binding python)
```
make
python setup.py install
```
4. I got python-olm installed
```
pip list | grep python-olm
python-olm         3.2.13
```

Problem:
When i run simple code => from olm import *, i got error:
```
Traceback (most recent call last):
  File "olm-test.py", line 1, in <module>
    from olm import *
  File "<my_dir>/lib/python3.8/site-packages/python_olm-3.2.13-py3.8-linux-x86_64.egg/olm/__init__.py", line 24, in <module>
    from .utility import ed25519_verify, OlmVerifyError, OlmHashError, sha256
  File "<my_dir>/lib/python3.8/site-packages/python_olm-3.2.13-py3.8-linux-x86_64.egg/olm/utility.py", line 39, in <module>
    from _libolm import ffi, lib  # type: ignore
ImportError: libolm.so.3: cannot open shared object file: No such file or directory
```

What am i doing wrong ?

**Comment by Giffari17** [comment]
In venv, i have this for olm lib:
![image](https://user-images.githubusercontent.com/86210172/199765031-350146d9-af14-45a8-90b7-9ebf08f17e2b.png)

**Comment by Giffari17** [comment]
After long time exploring, i made this works.
manually install:
libolm3, libolmdev

enter venv

run:
pip install python-olm

**Comment by 42Willow** [comment]
``

> libolm3

What commands did you use to install libolm3 and libolmdev? I am having the same problem and I've also spent a long time exploring 😓

**Comment by 42willow** [comment]
Never mind I fixed it, but now I'm getting this o.o
```
 File "/home/pi/element-bot/lib/python3.9/site-packages/python_olm-3.2.13-py3.9-linux-armv7l.egg/olm/utility.py", line 39, in <module>
    from _libolm import ffi, lib  # type: ignore
ImportError: /home/pi/element-bot/lib/python3.9/site-packages/python_olm-3.2.13-py3.9-linux-armv7l.egg/_libolm.abi3.so: undefined symbol: olm_account_last_error_code
```


EDIT: nevermind I fixed it! just reset raspberry pi os and kept trying (also installed x64bit version)

**Comment by Giffari17** [comment]
I just tried it again, these i'm using:

sudo apt install libolm3 libolm-dev
pip install python-olm

No error found here
