### ISSUE TITLE
PQXDH protocol / Quantum resistance

### ISSUE THREAD

**Issue by alexander-potemkin** [matrix-org/olm#87]
Following Signal's [recent news](https://signal.org/blog/pqxdh/), do you have any plans on implementing some more advanced encryption with quantum resistance? Or what's the perspective of Matrix.org on that?

Thanks in advance!

**Comment by uhoreg** [comment]
https://github.com/matrix-org/matrix-spec/issues/975 is the canonical issue for quantum resistance in Matrix
