### ISSUE TITLE
Please release 3.2.16 to pypi

### ISSUE THREAD

**Issue by abeluck** [matrix-org/olm#88]
The commit https://gitlab.matrix.org/matrix-org/olm/-/commit/bbdac4045dbd26967bc9c04d7269fa7966487a36 which landed in v3.2.16 (4 days ago as of writing) is quite important, could we please get a release of the latest python package to pypi?

**Comment by uhoreg** [comment]
Sorry, I had uploaded it, but forgot to update my script to upload to pypi rather than our GitLab registry.  I'm uploading to PyPi now.
