### ISSUE TITLE
 "@matrix-org/olm": "^3.2.15" works error

### ISSUE THREAD

**Issue by Xxs-7** [matrix-org/olm#93]
Issue Template

## Description
When running a demo(react and typescript) using @matrix-org/olm version ^3.2.15, I encounter the following error:

```
olm.js:26 Uncaught (in promise) 
RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0). Build with -sASSERTIONS for more info.
    at r (olm.js:26:147)
    at olm.js:32:407

localhost/:1 Uncaught (in promise) 
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0
localhost/:1 Uncaught (in promise) 
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0
```

It seems a wasm error inside the package, I could not figure out how to solve it, please help me!

Steps to Reproduce
1. create a react project
2. Install @matrix-org/olm version ^3.2.15.
3. Run the following code:
```javascript
Olm.init().then(() => {
  console.log('hello');
});
```
4. Observe the error in the console.

## Expected Behavior
The WebAssembly module should initialize without errors.

Actual Behavior
The error message expected magic word 00 61 73 6d, found 3c 21 64 6f appears, indicating an issue with WebAssembly module instantiation.

Environment
@matrix-org/olm Version: ^3.2.15
Browser: Chrome 127.0.***
OS:Mac
Other Dependencies: react 18

Additional Context
https://gitlab.matrix.org/matrix-org/olm/-/packages/2190
https://gitlab.matrix.org/matrix-org/olm/-/tree/master/javascript/demo

**Comment by Xxs-7** [comment]
As mentioned in https://github.com/matrix-org/olm/issues/65, the reason of this bug is Olm.init can't find the olm.wasm, but the olm.wasm is actually in node_modules/@matrix-org/olm/olm.wasm, after pnpm install @matrix-org/olm.
Further more, i did what https://github.com/matrix-org/olm/issues/65#issuecomment-966552831 commented, but get i new error: `ReferenceError: OLM_OPTIONS is not defined`
but OLM_OPTIONS is actually in https://gitlab.matrix.org/matrix-org/olm/-/blob/master/javascript/externs.js
How could i use npm package @matrix-org/olm in vite+react project, i am very frustrated~

**Comment by richvdh** [comment]
You'll need to make the `olm.wasm` file available over http somehow. I'm not familiar with Vite so can't help you.

libolm isn't maintained and I wouldn't recommend its use in a new project.
